<?php

namespace Somtum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-10-29 at 20:32:16.
 */
class RouterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Router
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Router();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert ('/index.php/Index/Model/Index/web?1234', array()) [==] array( '_mvc' => 'Model', '_dir' => 'Index', 'module' => 'Index', '_method' => 'web').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes()
    {

        $this->assertEquals(
          array('_mvc' => 'Model', '_dir' => 'Index', 'module' => 'Index', '_method' => 'web'), $this->object->parseRoutes('/index.php/Index/Model/Index/web?1234', array())
        );
    }

    /**
     * Generated from @assert ('/index.php/Index/Model/Index/web', array()) [==] array( '_mvc' => 'Model', '_dir' => 'Index', 'module' => 'Index', '_method' => 'web').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes2()
    {

        $this->assertEquals(
          array('_mvc' => 'Model', '_dir' => 'Index', 'module' => 'Index', '_method' => 'web'), $this->object->parseRoutes('/index.php/Index/Model/Index/web', array())
        );
    }

    /**
     * Generated from @assert ('/print.php/Css/View/Index', array()) [==] array( '_mvc' => 'View', '_dir' => 'Index', 'module' => 'Css').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes3()
    {

        $this->assertEquals(
          array('_mvc' => 'View', '_dir' => 'Index', 'module' => 'Css'), $this->object->parseRoutes('/print.php/Css/View/Index', array())
        );
    }

    /**
     * Generated from @assert ('/index/model/updateprofile.php', array()) [==] array( '_mvc' => 'model', '_dir' => 'updateprofile', 'module' => 'index').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes4()
    {

        $this->assertEquals(
          array('_mvc' => 'model', '_dir' => 'updateprofile', 'module' => 'index'), $this->object->parseRoutes('/index/model/updateprofile.php', array())
        );
    }

    /**
     * Generated from @assert ('/index.php/Alias/Model/Admin/Settings/save', array()) [==] array('module' => 'Alias', '_mvc' => 'Model', '_dir' => 'Admin/Settings', '_method' => 'save').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes5()
    {

        $this->assertEquals(
          array('module' => 'Alias', '_mvc' => 'Model', '_dir' => 'Admin/Settings', '_method' => 'save'), $this->object->parseRoutes('/index.php/Alias/Model/Admin/Settings/save', array())
        );
    }

    /**
     * Generated from @assert ('/css/view/index.php', array()) [==] array('module' => 'css', '_mvc' => 'view', '_dir' => 'index').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes6()
    {

        $this->assertEquals(
          array('module' => 'css', '_mvc' => 'view', '_dir' => 'index'), $this->object->parseRoutes('/css/view/index.php', array())
        );
    }

    /**
     * Generated from @assert ('/module.html', array()) [==] array('module' => 'module').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes7()
    {

        $this->assertEquals(
          array('module' => 'module'), $this->object->parseRoutes('/module.html', array())
        );
    }

    /**
     * Generated from @assert ('/index.php', array('_action' => 'one')) [==] array('_action' => 'one').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes8()
    {

        $this->assertEquals(
          array('_action' => 'one'), $this->object->parseRoutes('/index.php', array('_action' => 'one'))
        );
    }

    /**
     * Generated from @assert ('/admin_index.php', array('_action' => 'one')) [==] array('_action' => 'one', 'module' => 'admin_index').
     *
     * @covers Somtum\Router::parseRoutes
     */
    public function testParseRoutes9()
    {

        $this->assertEquals(
          array('_action' => 'one', 'module' => 'admin_index'), $this->object->parseRoutes('/admin_index.php', array('_action' => 'one'))
        );
    }
}