<?php

namespace Somtum;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2018-11-03 at 12:22:20.
 */
class TemplateTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Template
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Template();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * Generated from @assert ('', '', 'FileNotFound')->isEmpty() [==] true.
     *
     * @covers Somtum\Template::create
     */
    public function testCreate()
    {

        $this->assertTrue(
          \Somtum\Template::create('', '', 'FileNotFound')->isEmpty()
        );
    }

    /**
     * Generated from @assert ('FileNotFound') [throws] InvalidArgumentException.
     *
     * @covers Somtum\Template::createFromFile
     * @expectedException InvalidArgumentException
     */
    public function testCreateFromFile()
    {

        \Somtum\Template::createFromFile('FileNotFound');
    }

    /**
     * Generated from @assert ('/{TITLE}/', 'Title', '<b>{TITLE}</b>') [==] '<b>Title</b>'.
     *
     * @covers Somtum\Template::pregReplace
     */
    public function testPregReplace()
    {

        $this->assertEquals(
          '<b>Title</b>', \Somtum\Template::pregReplace('/{TITLE}/', 'Title', '<b>{TITLE}</b>')
        );
    }
}